[helix]
url = "https://github.com/helix-editor/helix/releases/download/${version}/helix-${version}-${architecture}-${os}.tar.xz"
rootPath = "helix-${version}-${architecture}-${os}"
compression = ".tar.xz"
filesToMakeExecutable = ["hx"]
version = "25.01.1"
[helix.checksums]
"x86_64-linux-25.01.1" = "TODO"

[ghostty]
# TODO

[nushell]
url = "https://github.com/nushell/nushell/releases/download/0.105.1/nu-${version}-${architecture}-unknown-${os}-gnu.tar.gz"
rootPath = "nu-${version}-${architecture}-unknown-${os}-gnu"
compression = ".tar.gz"
filesToMakeExecutable = ["nu"]
version = "0.105.1"
[nushell.checksums]
"x86_64-linux-0.105.1" = "TODO"
