[helix]
homepage = "https://helix-editor.com/"
url = "https://github.com/helix-editor/helix/releases/download/${version.main}/helix-${version.main}-${architecture}-${os}.tar.xz"
rootPath = "helix-${version.main}-${architecture}-${os}"
compression = ".tar.xz"
filesToMakeExecutable = ["hx"]
version.main = "25.01.1"
architectureNames.amd64 = "x86_64"
[helix.checksums]
# "x86_64-linux-25.01.1" = "TODO"

[ghostty]
homepage = "https://ghostty.org/"
# TODO

[gh-cli]
homepage = "https://cli.github.com/"
url = "https://github.com/cli/cli/releases/download/v${version.main}/gh_${version.main}_${os}_${architecture}.tar.gz"
rootPath = "gh_${version.main}_${os}_${architecture}/bin"
compression = ".tar.gz"
filesToMakeExecutable = ["gh"]
version.main = "2.75.0"
[gh-cli.checksums]
# "amd64-linux-2.75.0" = "TODO"

[act]
homepage = "https://nektosact.com/"
url = "https://github.com/nektos/act/releases/download/v${version.main}/act_${os}_${architecture}.tar.gz"
compression = ".tar.gz"
filesToMakeExecutable = ["act"]
version.main = "0.2.79"
architectureNames.amd64 = "x86_64"
[act.checksums]
# "x86_64-linux-0.2.79" = "TODO"

[nushell]
homepage = "https://www.nushell.sh/"
url = "https://github.com/nushell/nushell/releases/download/0.105.1/nu-${version.main}-${architecture}-unknown-${os}-gnu.tar.gz"
rootPath = "nu-${version.main}-${architecture}-unknown-${os}-gnu"
compression = ".tar.gz"
filesToMakeExecutable = ["nu"]
version.main = "0.105.1"
architectureNames.amd64 = "x86_64"
[nushell.checksums]
#"x86_64-linux-0.105.1" = 0x6501bc346e2ad6eecae3bcf7eee78ac21b1a03bdc4fda879a4d24793c1f08db7

[MuseScore]
homepage = "https://musescore.org/"
url = "https://cdn.jsdelivr.net/musescore/v${version.main}/MuseScore-Studio-${version.main}.${version.other}-${architecture}.AppImage"
compression = "none"
filesToMakeExecutable = ["."]
version.main = "4.5.2"
version.other = "251141401"
architectureNames.amd64 = "x86_64"
[MuseScore.checksums]
#"x86_64-linux-4.5.2-251141401" = "TODO"

[zig]
homepage = "https://ziglang.org/"
url = "https://ziglang.org/download/${version.main}/zig-${architecture}-${os}-${version.main}.tar.xz"
rootPath = "zig-${architecture}-${os}-${version.main}"
compression = ".tar.xz"
filesToMakeExecutable = ["zig"]
version.main = "0.14.1"
architectureNames.amd64 = "x86_64"
[zig.checksums]
#"x86_64-linux-0.14.1" = "TODO"

[zls]
homepage = "https://github.com/zigtools/zls"
url = "https://github.com/zigtools/zls/releases/download/${version.main}/zls-${architecture}-${os}.tar.xz"
compression = ".tar.xz"
filesToMakeExecutable = ["zls"]
version.main = "0.14.0"
architectureNames.amd64 = "x86_64"
[zls.checksums]
#"x86_64-linux-0.14.0" = "TODO"
