installationWarnings = ["Act uses docker by default, but docker has not been packaged. The plan is for bento to setup act to use podman by default once podman works because podman does not require root priviladges unlike docker."]
homepage = "https://nektosact.com/"
urlInMirror = "nektos/act/releases/download/v${version.main}/act_linux_${architecture}.tar.gz"
compression = ".tar.gz"
filesToMakeExecutable = ["act"]
mirrors = ["https://github.com"]

[version]
main = "0.2.79"

[architectureNames]
amd64 = "x86_64"

[checksums]
"nektos/act/releases/download/v0.2.79/act_linux_x86_64.tar.gz" = "b4c14df1a6e713a63e8e153534091a2e0d93a73538da301bd3aaa3c1f2a6f571"
