homepage = "https://github.com/linux-audit/audit-userspace"
urlInMirror = "packages/a/audit/audit-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org"]

[version]
main = "4.0.5-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"packages/a/audit/audit-4.0.5-1-x86_64.pkg.tar.zst" = "09d03362067b441b343df86d41025cd4be8ce2f10347e610fc8db2c389822ebc"
