homepage = "https://sourceware.org/bzip2/"
url = "https://archive.archlinux.org/packages/b/bzip2/bzip2-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "1.0.8-6"
architectureNames.amd64 = "x86_64"
