homepage = "https://cairographics.org/"
url = "https://archive.archlinux.org/packages/c/cairo/cairo-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "1.18.4-1"
architectureNames.amd64 = "x86_64"

[checksums]
"https://archive.archlinux.org/packages/c/cairo/cairo-1.18.4-1-x86_64.pkg.tar.zst" = "280a524ba7dce88990aace1496abd742b000a7c98a5ec6abd054a4b19f2f4c96"