homepage = "https://github.com/containers"
urlInMirror = "packages/c/containers-common/containers-common-${version.main}-any.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org"]

[version]
main = "1:0.64.1-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"packages/c/containers-common/containers-common-1:0.63.1-1-any.pkg.tar.zst" = "54fd28028b00feb084718f9fafc44dcae13c84ffb07d95a4dc58a3e6899a2cd5"
"packages/c/containers-common/containers-common-1:0.64.1-1-any.pkg.tar.zst" = "8355640ae889c95e576351a6d5850211c915d391a82759ef1525811af9ae7c2e"
