homepage = "https://github.com/containers"
urlInMirror = "containers-common-${version.main}-any.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org/packages/c/containers-common"]

[version]
main = "1:0.64.2-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"containers-common-1:0.64.1-1-any.pkg.tar.zst" = "8355640ae889c95e576351a6d5850211c915d391a82759ef1525811af9ae7c2e"
"containers-common-1:0.64.2-1-any.pkg.tar.zst" = "c986e61d362e4b5b3f7c3b1c75d031f346816552708aba29f20cbbfae4a65464"
