homepage = "https://github.com/containers"
url = "https://archive.archlinux.org/packages/c/containers-common/containers-common-${version.main}-any.pkg.tar.zst"
compression = ".tar.zst"
version.main = "1:0.63.1-1"
architectureNames.amd64 = "x86_64"
