installationWarnings = ["Cursor only works on x86_64, and bento has no way of knowing this"]
homepage = "https://cursor.com/"
licenses = ["Proprietary"]
urlInMirror = "production/${version.other}/linux/x64/Cursor-${version.main}-${architecture}.AppImage"
compression = "none"
filesToMakeExecutable = ["."]
mirrors = ["https://downloads.cursor.com"]

[version]
main = "1.4.2"
other = "d01860bc5f5a36b62f8a77cd42578126270db343"

[architectureNames]
amd64 = "x86_64"

[checksums]
"production/d01860bc5f5a36b62f8a77cd42578126270db343/linux/x64/Cursor-1.4.2-x86_64.AppImage" = "58c640d028c0a5c493ba9e052c8c7168eee130c66b24f6b062c7c25e714ae041"
