homepage = "https://www.freedesktop.org/wiki/Software/dbus/"
url = "https://archive.archlinux.org/packages/d/dbus/dbus-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "1.16.2-1"
architectureNames.amd64 = "x86_64"
