installationWarnings = ["You have to run `dprint init --global` before dprint works"]
homepage = "https://github.com/dprint/dprint"
urlInMirror = "${version.main}/dprint-${architecture}-unknown-linux-musl.zip"
compression = ".zip"
mirrors = ["https://github.com/dprint/dprint/releases/download"]

[version]
main = "0.51.1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"0.51.1/dprint-x86_64-unknown-linux-musl.zip" = "0bc7904de86cc70384a4d295902c69fc5239ed45ab19a7361216263d1a8cb572"
