homepage = "https://elm-lang.org/"
programmingLanguage = "Haskell"
compression = ".gz"
urlInMirror = "elm/compiler/releases/download/${version.main}/binary-for-linux-64-bit.gz"
filesToMakeExecutable = ["."]
mirrors = ["https://github.com"]

[version]
main = "0.19.1"

[checksums]
"elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz" = "e44af52bb27f725a973478e589d990a6428e115fe1bb14f03833134d6c0f155c"
