homepage = "https://libexpat.github.io/"
url = "https://archive.archlinux.org/packages/e/expat/expat-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "2.7.1-1"
architectureNames.amd64 = "x86_64"
