installationWarnings = ["Bento's fish package is partially disfunction as it cannot find it's asset files (see [this issue](https://github.com/fish-shell/fish-shell/issues/11765))"]
homepage = "https://fishshell.com/"
description = "Smart and user friendly shell intended mostly for interactive use"
urlInMirror = "fish-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org/packages/f/fish"]

[version]
main = "4.1.2-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"fish-4.0.2-1-x86_64.pkg.tar.zst" = "307242754bea69f45faedc54008c48c91d69e71f94684292500b74fe3d634a22"
"fish-4.1.2-1-x86_64.pkg.tar.zst" = "1058f821f69a2ebf964f048992bab5b5c0b6e4427f863a10db67ff007f18b0c9"

[directSharedLibraryDependencies]
"usr/bin/fish" = [
    "libpcre2-8.so.0",
    "libpcre2-32.so.0",
    "libgcc_s.so.1",
    "libm.so.6",
    "libc.so.6",
]
"usr/bin/fish_indent" = [
    "libpcre2-8.so.0",
    "libpcre2-32.so.0",
    "libgcc_s.so.1",
    "libm.so.6",
    "libc.so.6",
]
"usr/bin/fish_key_reader" = [
    "libpcre2-32.so.0",
    "libgcc_s.so.1",
    "libc.so.6",
]
