homepage = "https://fishshell.com/"
description = "Smart and user friendly shell intended mostly for interactive use"
url = "https://archive.archlinux.org/packages/f/fish/fish-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"

[version]
main = "4.0.2-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"https://archive.archlinux.org/packages/f/fish/fish-4.0.2-1-x86_64.pkg.tar.zst" = "307242754bea69f45faedc54008c48c91d69e71f94684292500b74fe3d634a22"

[directlyDependentSharedLibraries]
"usr/bin/fish" = [
  "libpcre2-8.so.0",
  "libpcre2-32.so.0",
  "libgcc_s.so.1",
  "libm.so.6",
  "libc.so.6",
]
"usr/bin/fish_indent" = [
  "libpcre2-8.so.0",
  "libpcre2-32.so.0",
  "libgcc_s.so.1",
  "libm.so.6",
  "libc.so.6",
]
"usr/bin/fish_key_reader" = [
  "libpcre2-32.so.0",
  "libgcc_s.so.1",
  "libc.so.6",
]
