homepage = "https://www.freedesktop.org/wiki/Software/fontconfig/"
urlInMirror = "packages/f/fontconfig/fontconfig-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org"]

[version]
main = "2:2.17.1-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"packages/f/fontconfig/fontconfig-2:2.17.1-1-x86_64.pkg.tar.zst" = "64dcc7ccaa5460b93ce1c76a9e104bcbb373d3d15fb5abc01a1192f4607e9d2e"
