homepage = "https://freetype.org/"
url = "https://archive.archlinux.org/packages/f/freetype2/freetype2-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "2.13.3-3"
architectureNames.amd64 = "x86_64"
[checksums]
#"x86_64-2.13.3-3" = "TODO"
