homepage = "https://freetype.org/"
urlInMirror = "packages/f/freetype2/freetype2-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org"]

[version]
main = "2.13.3-3"

[architectureNames]
amd64 = "x86_64"

[checksums]
"packages/f/freetype2/freetype2-2.13.3-3-x86_64.pkg.tar.zst" = "130217614d85ad4a7bc4a565e2ef2be51e71712287263bc7463fc07f4bc2f985"
