homepage = "https://gitlab.com/chinstrap/gammastep"
urlInMirror = "gammastep-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org/packages/g/gammastep"]

[version]
main = "2.0.11-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"gammastep-2.0.11-1-x86_64.pkg.tar.zst" = "981188856d975485839ce82848e57e8638fd04715658768d3db9f9d7166d04bd"
