homepage = "https://gcc.gnu.org/"
url = "https://archive.archlinux.org/packages/g/gcc-libs/gcc-libs-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "15.1.1+r7+gf36ec88aa85a-1"
architectureNames.amd64 = "x86_64"

[checksums]
"https://archive.archlinux.org/packages/g/gcc-libs/gcc-libs-15.1.1+r7+gf36ec88aa85a-1-x86_64.pkg.tar.zst" = "6eedd2e4afc53e377b5f1772b5d413de3647197e36ce5dc4a409f993668aa5ed"