homepage = "https://ghostty.org/"
programmingLanguage = "Zig"
url = "https://archive.archlinux.org/packages/g/ghostty/ghostty-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "1.1.3-1"
architectureNames.amd64 = "x86_64"
rootPath = "usr"
filesToMakeExecutable = ["bin/ghostty"]

[directlyDependentSharedLibraries]
"bin/ghostty" = [
  "libfreetype.so.6",
  "libharfbuzz.so.0",
  "libfontconfig.so.1",
  "libonig.so.5",
  "libgtk-4.so.1",
  "libgio-2.0.so.0",
  "libgobject-2.0.so.0",
  "libglib-2.0.so.0",
  "libadwaita-1.so.0",
  "libX11.so.6",
  "libwayland-client.so.0",
  "libm.so.6",
  "libc.so.6",
  "ld-linux-x86-64.so.2",
]

[env]
"bin/ghostty" = {"GHOSTTY_RESOURCES_DIR" = "${ghostty}/share/ghostty"}

[checksums]
"https://archive.archlinux.org/packages/g/ghostty/ghostty-1.1.3-1-x86_64.pkg.tar.zst" = "072f7d1ca3fb58a180cd38e3811b16e14203596ad59e80dd27ba4c4cf2a15275"
