homepage = "https://github.com/ghostty-org/ghostty"
description = "Terminfo for ghostty"
licenses = ["MIT"]
urlInMirror = "packages/g/ghostty-terminfo/ghostty-terminfo-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org"]

[version]
main = "1.1.3-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"packages/g/ghostty-terminfo/ghostty-terminfo-1.1.3-1-x86_64.pkg.tar.zst" = "05138278ee61deb47a1100a260711e7dffe9881c7de293ea54adea810e0c87e0"
