installationWarnings = [
    "Ghostty only works on x86_64, and bento has no way of knowing this",
]
knownIssues = [
    "The close button is incorrectly rendered when you hover over it",
    "Ghostty only works with glibc version 2.41, and not version 2.42 for some reason",
    "Ghostty only works with pango 1.56, and not version 1.57 for some reason",
]
homepage = "https://ghostty.org/"
programmingLanguage = "Zig"
urlInMirror = "godalming123/ghostty-bin/releases/download/v${version.main}/ghostty.tar.zst"
compression = ".tar.zst"
mirrors = ["https://github.com"]

[version]
main = "1.2.2"

[directSharedLibraryDependencies]
"bin/ghostty" = [
    "libfreetype.so.6",
    "libharfbuzz.so.0",
    "libfontconfig.so.1",
    "libonig.so.5",
    "libgtk-4.so.1",
    "libgio-2.0.so.0",
    "libgobject-2.0.so.0",
    "libglib-2.0.so.0",
    "libadwaita-1.so.0",
    "libX11.so.6",
    "libwayland-client.so.0",
    "libm.so.6",
    "libc.so.6",
    "ld-linux-x86-64.so.2",
    "libgtk4-layer-shell.so.0",
]

[env."bin/ghostty"]
GHOSTTY_RESOURCES_DIR = "${ghostty}/share/ghostty"

[checksums]
"godalming123/ghostty-bin/releases/download/v1.1.3/ghostty.tar.zst" = "cc022629f8ec915ea423d1cdd4cc29e312799f604032e38263796b66cd59111f"
"godalming123/ghostty-bin/releases/download/v1.2.0/ghostty.tar.zst" = "d2e4f9590568c66cf54f0efb32f2d9a5c7761ca596c16afe538de8458306ade3"
"godalming123/ghostty-bin/releases/download/v1.2.2/ghostty.tar.zst" = "1aa7cb2273130d743849e61f8bd07e7266c99631ff5cafb4e0a1831e91d01cb3"
