homepage = "https://gleam.run/"
description = "Gleam is a friendly language for building type-safe systems that scale!"
licenses = ["Apache 2.0"]
programmingLanguge = "rust"
urlInMirror = "gleam-lang/gleam/releases/download/v${version.main}/gleam-v${version.main}-${architecture}-unknown-linux-musl.tar.gz"
compression = ".tar.gz"
mirrors = ["https://github.com"]

[version]
main = "1.12.0"

[architectureNames]
amd64 = "x86_64"

[checksums]
"gleam-lang/gleam/releases/download/v1.12.0/gleam-v1.12.0-x86_64-unknown-linux-musl.tar.gz" = "039a87bd7294d3cfd2425f56e8ffef508b170ecec42e760806833fb1e0319d49"
