homepage = "https://gitlab.gnome.org/GNOME/glib"
url = "https://archive.archlinux.org/packages/g/glib2/glib2-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "2.84.3-1"
architectureNames.amd64 = "x86_64"

[checksums]
"https://archive.archlinux.org/packages/g/glib2/glib2-2.84.3-1-x86_64.pkg.tar.zst" = "91f161f75682136183661bcae3ec836a4be107e5e8060d71fdf509090e212b31"
