homepage = "https://gmplib.org/"
urlInMirror = "gmp-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org/packages/g/gmp"]

[version]
main = "6.3.0-2"

[architectureNames]
amd64 = "x86_64"

[checksums]
"gmp-6.3.0-2-x86_64.pkg.tar.zst" = "286c23ed38d46f803a19d06ca46dc67d96805f7805f7b9818cf9c0ca65a69326"
