homepage = "https://gmplib.org/"
url = "https://archive.archlinux.org/packages/g/gmp/gmp-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "6.3.0-2"
architectureNames.amd64 = "x86_64"
