homepage = "https://www.gnupg.org/related_software/gpgme/"
urlInMirror = "gpgme-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org/packages/g/gpgme"]

[version]
main = "2.0.0-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"gpgme-2.0.0-1-x86_64.pkg.tar.zst" = "f63e5510da98ea38777b6cb3c2fa44d2240b48190c5c2e4597c4e9889ab087f7"
