homepage = "https://gstreamer.freedesktop.org/"
urlInMirror = "gst-plugins-base-libs-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org/packages/g/gst-plugins-base-libs"]

[version]
main = "1.26.7-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"gst-plugins-base-libs-1.26.4-1-x86_64.pkg.tar.zst" = "ddc02326aa5195b9280eec5137726e2d81ea263a6ae6c1a85fbcaf0d12497a45"
"gst-plugins-base-libs-1.26.5-2-x86_64.pkg.tar.zst" = "33c2efbbc4070b2438df207e14cd13b87c461a01967b0a0fb71a7c584e0f1f48"
"gst-plugins-base-libs-1.26.7-1-x86_64.pkg.tar.zst" = "f26be990d81cd57d9ec1d17379d224ba3758edb469a27453caa5a429cf3842a1"
