homepage = "https://github.com/wmww/gtk4-layer-shell"
url = "https://archive.archlinux.org/packages/g/gtk4-layer-shell/gtk4-layer-shell-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "1.0.3-1"
architectureNames.amd64 = "x86_64"

[checksums]
"https://archive.archlinux.org/packages/g/gtk4-layer-shell/gtk4-layer-shell-1.0.3-1-x86_64.pkg.tar.zst" = "c8d69e83cbaffe4a438ac28c3944afaa5edc920477829c7e92a75942ed479e5c"
