homepage = "https://harfbuzz.github.io/"
url = "https://archive.archlinux.org/packages/h/harfbuzz/harfbuzz-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "11.2.1-1"
architectureNames.amd64 = "x86_64"

[checksums]
"https://archive.archlinux.org/packages/h/harfbuzz/harfbuzz-11.2.1-1-x86_64.pkg.tar.zst" = "9ffe4e898c506a568fcb6d7e23da8f11a92332d8bb27b343cf00bf4763e5a466"
