homepage = "https://helix-editor.com/"
programmingLanguage = "Rust"
url = "https://github.com/helix-editor/helix/releases/download/${version.main}/helix-${version.main}-${architecture}-linux.tar.xz"
rootPath = "helix-${version.main}-${architecture}-linux"
compression = ".tar.xz"
filesToMakeExecutable = ["hx"]
version.main = "25.07.1"
architectureNames.amd64 = "x86_64"

[checksums]
"https://github.com/helix-editor/helix/releases/download/25.07.1/helix-25.07.1-x86_64-linux.tar.xz" = "3f08e63ecd388fff657ad39722f88bb03dcf326f1f2da2700d99e1dc40ab2e8b"
