homepage = "https://www.cl.cam.ac.uk/~mgk25/jbigkit/"
url = "https://archive.archlinux.org/packages/j/jbigkit/jbigkit-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"

[version]
main = "2.1-8"

[architectureNames]
amd64 = "x86_64"

[checksums]
"https://archive.archlinux.org/packages/j/jbigkit/jbigkit-2.1-8-x86_64.pkg.tar.zst" = "ca53fa884681273162aadcf99c30514a7010d5e621eb0a5ae491500ae8dc52c9"
