homepage = "http://www.littlecms.com/"
urlInMirror = "packages/l/lcms2/lcms2-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org"]

[version]
main = "2.17-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"packages/l/lcms2/lcms2-2.17-1-x86_64.pkg.tar.zst" = "f2ba63564307d3bd532f12ef527aca12762e6213e35aacf256622129a638972c"
