homepage = "http://www.littlecms.com/"
url = "https://archive.archlinux.org/packages/l/lcms2/lcms2-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "2.17-1"
architectureNames.amd64 = "x86_64"
