homepage = "https://github.com/gokcehan/lf"
description = "A terminal file manager inspired by ranger"
licenses = ["MIT"]
url = "https://archive.archlinux.org/packages/l/lf/lf-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "36-1"
architectureNames.amd64 = "x86_64"

[checksums]
"https://archive.archlinux.org/packages/l/lf/lf-36-1-x86_64.pkg.tar.zst" = "0d3dedd0e51513299e923430eb2cbd4f91ce59e2a3198a0f6354c8ad0fb34de4"

[directlyDependentSharedLibraries]
"lf/usr/bin/lf" = [
  "libresolv.so.2",
  "libc.so.6",
]
