homepage = "https://www.gnupg.org/related_software/libassuan/"
url = "https://archive.archlinux.org/packages/l/libassuan/libassuan-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "3.0.0-1"
architectureNames.amd64 = "x86_64"
