homepage = "https://gitlab.gnome.org/GNOME/libadwaita/"
url = "https://archive.archlinux.org/packages/l/libadwaita/libadwaita-1:${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "1.7.5-1"
architectureNames.amd64 = "x86_64"

[checksums]
"https://archive.archlinux.org/packages/l/libadwaita/libadwaita-1:1.7.5-1-x86_64.pkg.tar.zst" = "cdb980594428c4bf8d46d25538cae9b4b783228e3ab505c12bd40f793b81e33a"
