homepage = "https://openprinting.github.io/cups/"
urlInMirror = "libcups-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org/packages/l/libcups"]

[version]
main = "2:2.4.12-2"

[architectureNames]
amd64 = "x86_64"

[checksums]
"libcups-2:2.4.12-2-x86_64.pkg.tar.zst" = "91a0c83de714a8c7fdef5e38f32f70963a545fd62c5797ccffc7090d668c4a58"
