homepage = "https://gitlab.gnome.org/World/libcloudproviders"
url = "https://archive.archlinux.org/packages/l/libcloudproviders/libcloudproviders-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "0.3.6-2"
architectureNames.amd64 = "x86_64"
