homepage = "https://sites.google.com/site/fullycapable/"
urlInMirror = "libcap-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org/packages/l/libcap"]

[version]
main = "2.78-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"libcap-2.76-1-x86_64.pkg.tar.zst" = "2b8e51caff26ef7d70aea69b0c079eda5f942010c7f7db88b064228c845a7cbb"
"libcap-2.77-1-x86_64.pkg.tar.zst" = "16a575cf5266f6187d0a11930f8cfa9ba38df92a842f430c9e965dba689063bd"
"libcap-2.78-1-x86_64.pkg.tar.zst" = "3e984fe1d323b1c5a5fc60fef005776a4882fbca913d6fe3c41ad11128929ed1"
