homepage = "https://linux.thai.net/projects/datrie"
url = "https://archive.archlinux.org/packages/l/libdatrie/libdatrie-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "0.2.13-4"
architectureNames.amd64 = "x86_64"
