homepage = "https://sourceware.org/libffi/"
urlInMirror = "libffi-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org/packages/l/libffi"]

[version]
main = "3.5.2-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"libffi-3.5.1-1-x86_64.pkg.tar.zst" = "2a5df57eb1ec875b8fd825baf5eb70db2d487d7652532415b4bba38037afbb1e"
"libffi-3.5.2-1-x86_64.pkg.tar.zst" = "6855aa68ae506c124f9e62c6be3dd40dd750a050d7126d5265118128638da5c3"
