homepage = "https://www.gnupg.org/"
url = "https://archive.archlinux.org/packages/l/libgpg-error/libgpg-error-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "1.55-1"
architectureNames.amd64 = "x86_64"
