homepage = "https://www.gnu.org/software/libidn/#libidn2"
url = "https://archive.archlinux.org/packages/l/libidn2/libidn2-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "2.3.7-1"
architectureNames.amd64 = "x86_64"
