homepage = "https://libjpeg-turbo.org/"
url = "https://archive.archlinux.org/packages/l/libjpeg-turbo/libjpeg-turbo-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "3.1.1-1"
architectureNames.amd64 = "x86_64"

[checksums]
#"x86_64-linux-3.1.1-1" = "TODO"
