homepage = "http://www.libpng.org/pub/png/libpng.html"
url = "https://archive.archlinux.org/packages/l/libpng/libpng-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"

[version]
main = "1.6.50-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"https://archive.archlinux.org/packages/l/libpng/libpng-1.6.50-1-x86_64.pkg.tar.zst" = "aede8f9ec34ed258692541afe9b42929be7579b8e721cffa55c56705eed10f0b"
