homepage = "https://wiki.gnome.org/Projects/LibRsvg"
url = "https://archive.archlinux.org/packages/l/librsvg/librsvg-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "2:2.60.0-2"
architectureNames.amd64 = "x86_64"

[checksums]
"https://archive.archlinux.org/packages/l/librsvg/librsvg-2:2.60.0-2-x86_64.pkg.tar.zst" = "50e158c76479d85e65b91b624059d97961c2a1c18efa0388dfbfb295b2dbd230"