homepage = "https://wiki.gnome.org/Projects/LibRsvg"
url = "https://archive.archlinux.org/packages/l/librsvg/librsvg-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "2:2.60.0-2"
architectureNames.amd64 = "x86_64"
