homepage = "https://github.com/seccomp/libseccomp"
url = "https://archive.archlinux.org/packages/l/libseccomp/libseccomp-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "2.5.6-1"
architectureNames.amd64 = "x86_64"
