homepage = "https://www.gnu.org/software/libtasn1/"
urlInMirror = "libtasn1-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org/packages/l/libtasn1"]

[version]
main = "4.20.0-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"libtasn1-4.20.0-1-x86_64.pkg.tar.zst" = "f3883e75f33797b241032a2cfa60cb5caa8636914b42f8fb7ea9b2eb23d6f837"
