homepage = "https://linux.thai.net/projects/libthai"
urlInMirror = "libthai-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org/packages/l/libthai"]

[version]
main = "0.1.29-3"

[architectureNames]
amd64 = "x86_64"

[checksums]
"libthai-0.1.29-3-x86_64.pkg.tar.zst" = "40729f2231d3b1829663e451b61edd5163fcadf578e600bb386568a207427058"
