homepage = "https://www.nongnu.org/libunwind/"
url = "https://archive.archlinux.org/packages/l/libunwind/libunwind-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "1.8.2-1"
architectureNames.amd64 = "x86_64"
