homepage = "https://www.nongnu.org/libunwind/"
urlInMirror = "packages/l/libunwind/libunwind-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org"]

[version]
main = "1.8.2-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"packages/l/libunwind/libunwind-1.8.2-1-x86_64.pkg.tar.zst" = "74ba64398637c2dad73f0ed09cee63a83a0f9a67f1484e6fea5a6223ff165d55"
