homepage = "https://github.com/JuliaStrings/utf8proc"
url = "https://archive.archlinux.org/packages/l/libutf8proc/libutf8proc-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "2.10.0-1"
architectureNames.amd64 = "x86_64"
