homepage = "https://www.gnu.org/software/libunistring/"
urlInMirror = "libunistring-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org/packages/l/libunistring"]

[version]
main = "1.3-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"libunistring-1.3-1-x86_64.pkg.tar.zst" = "914f6602e4aeefa48fdba88a7432763d088c854844589950fbb5426e44582741"
