homepage = "https://github.com/libuv/libuv"
urlInMirror = "libuv-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org/packages/l/libuv"]

[version]
main = "1.51.0-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"libuv-1.51.0-1-x86_64.pkg.tar.zst" = "4a4e992621b881a221becb6b9669bb4092ffebec8d87bd90f235866356cc5c35"
