homepage = "https://xorg.freedesktop.org/"
url = "https://archive.archlinux.org/packages/l/libxau/libxau-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "1.0.12-1"
architectureNames.amd64 = "x86_64"
