homepage = "https://gitlab.freedesktop.org/xorg/lib/libxdmcp"
urlInMirror = "packages/l/libxdmcp/libxdmcp-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org"]

[version]
main = "1.1.5-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"packages/l/libxdmcp/libxdmcp-1.1.5-1-x86_64.pkg.tar.zst" = "1c4b370157e4b092334fa5404508c52a8214c072b1ab6e1dc8d3f6eea6db2b0b"
