homepage = "https://xorg.freedesktop.org/"
urlInMirror = "libxinerama-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org/packages/l/libxinerama"]

[version]
main = "1.1.5-2"

[architectureNames]
amd64 = "x86_64"

[checksums]
"libxinerama-1.1.5-2-x86_64.pkg.tar.zst" = "05a41224c7819853f5d79c2e28c8679d6a534a535d45a462ccb05fa8d58b05ad"
