homepage = "https://xkbcommon.org/"
url = "https://archive.archlinux.org/packages/l/libxkbcommon/libxkbcommon-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "1.10.0-1"
architectureNames.amd64 = "x86_64"
