homepage = "https://xorg.freedesktop.org/"
url = "https://archive.archlinux.org/packages/l/libxrandr/libxrandr-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "1.5.4-1"
architectureNames.amd64 = "x86_64"
