homepage = "https://gitlab.freedesktop.org/xorg/lib/libxext"
url = "https://archive.archlinux.org/packages/l/libxext/libxext-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "1.3.6-1"
architectureNames.amd64 = "x86_64"

[checksums]
"https://archive.archlinux.org/packages/l/libxext/libxext-1.3.6-1-x86_64.pkg.tar.zst" = "a6e51c38f10bf22728091c71fac64c3e02ccb37b847dd953773d23d4657560a3"