homepage = "https://xorg.freedesktop.org"
urlInMirror = "packages/l/libxi/libxi-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org"]

[version]
main = "1.8.2-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"packages/l/libxi/libxi-1.8.2-1-x86_64.pkg.tar.zst" = "7d56bf8dcc4a544a838e6d90504df8e3927176224dc07f9550153e57d07bb3f4"
