homepage = "https://gitlab.freedesktop.org/xorg/lib/libxcb"
url = "https://archive.archlinux.org/packages/l/libxcb/libxcb-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "1.17.0-1"
architectureNames.amd64 = "x86_64"
