homepage = "https://xorg.freedesktop.org/"
urlInMirror = "libxrender-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org/packages/l/libxrender"]

[version]
main = "0.9.12-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"libxrender-0.9.12-1-x86_64.pkg.tar.zst" = "fed0389073d5b107074eaab48cefcc2716e607865142cde5b579c8ceeefea142"
