homepage = "https://gitlab.gnome.org/GNOME/libxml2/-/wikis/home"
urlInMirror = "libxml2-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org/packages/l/libxml2"]

[version]
main = "2.14.6-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"libxml2-2.14.5-1-x86_64.pkg.tar.zst" = "098b504c15b9e319706aa3e882ca155ff87449a5ac3851f1994dc57706a53c13"
"libxml2-2.14.6-1-x86_64.pkg.tar.zst" = "fe52c0d16cf2ced092477a0cbe57232a77d26acf22625f503cc795a1d653e4ab"
