homepage = "https://gitlab.freedesktop.org/xorg/lib/libxdmcp"
url = "https://archive.archlinux.org/packages/l/libxdmcp/libxdmcp-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "1.1.5-1"
architectureNames.amd64 = "x86_64"
