homepage = "https://xorg.freedesktop.org/"
url = "https://archive.archlinux.org/packages/l/libxfixes/libxfixes-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "6.0.1-2"
architectureNames.amd64 = "x86_64"
