homepage = "https://gitlab.freedesktop.org/xorg/lib/libxcb"
urlInMirror = "libxcb-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org/packages/l/libxcb"]

[version]
main = "1.17.0-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"libxcb-1.17.0-1-x86_64.pkg.tar.zst" = "2b2e7ac64b1d56c08a227c10bcab179605f2773f31db0a8c89f49f4e5b2f1292"
