installationWarnings = ["Lilipod only supports AMD64, and bento has no way of knowing this"]
homepage = "https://github.com/89luca89/lilipod"
urlInMirror = "89luca89/lilipod/releases/download/v${version.main}/lilipod-linux-${architecture}"
compression = "none"
filesToMakeExecutable = ["."]
mirrors = ["https://github.com"]

[version]
main = "0.0.3"

[checksums]
"89luca89/lilipod/releases/download/v0.0.3/lilipod-linux-amd64" = "e781e67fd2eb42150f9bbcfd8338d9c248c27f061e720508ffc471731ae0001b"
