homepage = "https://www.oberhumer.com/opensource/lzo"
urlInMirror = "packages/l/lzo/lzo-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org"]

[version]
main = "2.10-5"

[architectureNames]
amd64 = "x86_64"

[checksums]
"packages/l/lzo/lzo-2.10-5-x86_64.pkg.tar.zst" = "dd5ec871aea5ddfd38d4a25539e966dc05e75d6969ebc31917c8d25b97ccd69e"
