homepage = "https://invisible-island.net/ncurses/ncurses.html"
description = "System V Release 4.0 curses emulation library"
licenses = ["MIT-open-group"]
urlInMirror = "ncurses-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org/packages/n/ncurses"]

[version]
main = "6.5-4"

[architectureNames]
amd64 = "x86_64"

[checksums]
"ncurses-6.5-4-x86_64.pkg.tar.zst" = "2d06710b287264cbf2e27fdd25f99fb080b2e8ecff53302af965435c0b83ec6a"

[directSharedLibraryDependencies]
"usr/bin/tic" = [
    "libncursesw.so.6",
    "libc.so.6",
]
"usr/bin/clear" = [
    "libncursesw.so.6",
    "libc.so.6",
]
"usr/bin/infocmp" = [
    "libncursesw.so.6",
    "libc.so.6",
]
"usr/bin/tset" = [
    "libncursesw.so.6",
    "libc.so.6",
]
"usr/bin/tabs" = [
    "libncursesw.so.6",
    "libc.so.6",
]
"usr/bin/toe" = [
    "libncursesw.so.6",
    "libc.so.6",
]
"usr/bin/tput" = [
    "libncursesw.so.6",
    "libc.so.6",
]
