homepage = "https://neovim.io"
rootPath = "nvim-linux-${architecture}"
url = "https://github.com/neovim/neovim/releases/download/v${version.main}/nvim-linux-${architecture}.tar.gz"
compression = ".tar.gz"
version.main = "0.11.3"
architectureNames.amd64 = "x86_64"

[directlyDependentSharedLibraries]
"bin/nvim" = [
  "libm.so.6",
  "libgcc_s.so.1",
  "libc.so.6",
  "ld-linux-x86-64.so.2",
]
