homepage = "https://nodejs.org/"
url = "https://archive.archlinux.org/packages/n/nodejs/nodejs-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "24.5.0-1"
architectureNames.amd64 = "x86_64"

[checksums]
"https://archive.archlinux.org/packages/n/nodejs/nodejs-24.5.0-1-x86_64.pkg.tar.zst" = "b57d2275136c6f17b9c0de731bf8d6da981947738431288e5638bfd21dc1b5c5"

[directlyDependentSharedLibraries]
"usr/bin/node" = [
  "libz.so.1",
  "libuv.so.1",
  "libsimdjson.so.26",
  "libbrotlidec.so.1",
  "libbrotlienc.so.1",
  "libcares.so.2",
  "libnghttp2.so.14",
  "libcrypto.so.3",
  "libssl.so.3",
  "libicui18n.so.76",
  "libicuuc.so.76",
  "libstdc++.so.6",
  "libm.so.6",
  "libgcc_s.so.1",
  "libc.so.6",
  "ld-linux-x86-64.so.2",
]
