homepage = "https://nodejs.org/"
url = "https://archive.archlinux.org/packages/n/nodejs/nodejs-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"

[version]
main = "24.7.0-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"https://archive.archlinux.org/packages/n/nodejs/nodejs-24.6.0-1-x86_64.pkg.tar.zst" = "a04a5291e16da1d9f86a01d46f9189ee206b5fc5805e7ab1a60917f86f16018c"
"https://archive.archlinux.org/packages/n/nodejs/nodejs-24.7.0-1-x86_64.pkg.tar.zst" = "74842de6cf7a024bc8d7003893e77129e38f31c6ec547e663271ed6b4b66587b"

[directlyDependentSharedLibraries]
"usr/bin/node" = [
    "libz.so.1",
    "libuv.so.1",
    "libsimdjson.so.26",
    "libbrotlidec.so.1",
    "libbrotlienc.so.1",
    "libcares.so.2",
    "libnghttp2.so.14",
    "libcrypto.so.3",
    "libssl.so.3",
    "libicui18n.so.76",
    "libicuuc.so.76",
    "libstdc++.so.6",
    "libm.so.6",
    "libgcc_s.so.1",
    "libc.so.6",
    "ld-linux-x86-64.so.2",
]
