homepage = "https://github.com/nodejs/node-gyp"
description = "Node.js native addon build tool"
licenses = ["MIT"]
url = "https://archive.archlinux.org/packages/n/node-gyp/node-gyp-${version.main}-any.pkg.tar.zst"
compression = ".tar.zst"
version.main = "11.3.0-1"
architectureNames.amd64 = "x86_64"

[checksums]
"https://archive.archlinux.org/packages/n/node-gyp/node-gyp-11.3.0-1-any.pkg.tar.zst" = "4a7688e8a073a7eaa493c2615f048155bf460ae38d048010c4252d2c0dddd1cb"

[directlyDependentSharedLibraries]