homepage = "https://github.com/npm/nopt"
description = "Node/npm Option Parsing library"
licenses = ["custom:ISC"]
urlInMirror = "packages/n/nodejs-nopt/nodejs-nopt-${version.main}-any.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org"]

[version]
main = "7.2.1-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"packages/n/nodejs-nopt/nodejs-nopt-7.2.1-1-any.pkg.tar.zst" = "272efa4c79c657d997fc56834311f8d5cf118da18a0646bc93319c4b10ed6b42"
