homepage = "https://www.nushell.sh/"
programmingLanguage = "Rust"
urlInMirror = "nushell/nushell/releases/download/${version.main}/nu-${version.main}-${architecture}-unknown-linux-gnu.tar.gz"
rootPath = "nu-${version.main}-${architecture}-unknown-linux-gnu"
compression = ".tar.gz"
filesToMakeExecutable = ["nu"]
mirrors = ["https://github.com"]

[version]
main = "0.106.1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"nushell/nushell/releases/download/0.106.1/nu-0.106.1-x86_64-unknown-linux-gnu.tar.gz" = "4f0688c71a36ba48a253e10876b5b101c3343f4a4deb19c446906b4572c340c9"
