homepage = "https://github.com/DanielGavin/ols"
programmingLanguage = "Odin"
urlInMirror = "latest%2F${version.main}/${architecture}-linux-gnu-odinfmt"
compression = "none"
filesToMakeExecutable = ["."]
mirrors = ["https://github.com/godalming123/ols-bin/releases/download"]

[version]
main = "2025-09-16"

[directlyDependentSharedLibraries]
"." = [
  "libm.so.6",
  "libc.so.6",
]

[checksums]
"latest%2F2025-09-06/amd64-linux-gnu-odinfmt" = "843c882c35dabca7349ed1e49d876d7655d4982776c8cf8657dd2d8a6fe6c7c3"
"latest%2F2025-09-16/amd64-linux-gnu-odinfmt" = "eb1307de7e00b66fba6e334d6e70313f674d65db8a510b7f1ef23136d2968678"
