homepage = "https://odin-lang.org/"
description = "Data-oriented programming language"
licenses = ["BSD-3-Clause"]
urlInMirror = "odin-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org/packages/o/odin"]

[version]
main = "dev_2025_09-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"odin-dev_2025_08-1-x86_64.pkg.tar.zst" = "31f108ed6db4b1353aacd0d83370ae56b1572cef6347a30e4e732bbae8ad4e22"
"odin-dev_2025_08-2-x86_64.pkg.tar.zst" = "e84072073ee4aeea15010dab3fe61ae1602138b9efaaff2c3214e5b6d66d2654"
"odin-dev_2025_09-1-x86_64.pkg.tar.zst" = "14f151072366e4977b76bac8809749633e911a9ea7885e15b59113cd7278eacf"

[directlyDependentSharedLibraries]
"usr/lib/odin/odin" = [
    "libm.so.6",
    "libstdc++.so.6",
    "libLLVM.so.20.1",
    "libgcc_s.so.1",
    "libc.so.6",
]
