homepage = "https://github.com/DanielGavin/ols"
programmingLanguage = "Odin"
urlInMirror = "latest%2F${version.main}/${architecture}-linux-gnu-ols"
compression = "none"
filesToMakeExecutable = ["."]
mirrors = ["https://github.com/godalming123/ols-bin/releases/download"]
executableDependencies = [["odin", "usr/lib/odin/odin"]]

[version]
main = "2025-09-23"

[directSharedLibraryDependencies]
"." = [
  "libm.so.6",
  "libc.so.6",
]

[checksums]
"latest%2F2025-09-06/amd64-linux-gnu-ols" = "ec87e8a1476e13a8e1097e540f0183176a824685826f269bcb52a55b0f8fbb5d"
"latest%2F2025-09-16/amd64-linux-gnu-ols" = "7cbf6f891d30100e81b512ce6cd95c4e71caf437cbea7813117af3fed226f99d"
"latest%2F2025-09-23/amd64-linux-gnu-ols" = "fcb63feac560b4b598d2ccddaf2c23b1572be372551f65409774f756d06cc860"
