homepage = "https://github.com/kkos/oniguruma"
urlInMirror = "oniguruma-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org/packages/o/oniguruma"]

[version]
main = "6.9.10-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"oniguruma-6.9.10-1-x86_64.pkg.tar.zst" = "25b7266753b04ed80dd771b7499d2750ad859a90fa87b37b891687891c108efe"
