homepage = "https://gstreamer.freedesktop.org/modules/orc.html"
urlInMirror = "orc-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org/packages/o/orc"]

[version]
main = "0.4.41-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"orc-0.4.41-1-x86_64.pkg.tar.zst" = "360a9f24cce9f9b7abd3406c465c9a32991c4f060ba6b9c55200c869c1dfad7c"
