homepage = "https://www.pango.org/"
url = "https://archive.archlinux.org/packages/p/pango/pango-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "1:1.56.4-1"
architectureNames.amd64 = "x86_64"
