homepage = "https://gitlab.freedesktop.org/pixman/pixman"
urlInMirror = "packages/p/pixman/pixman-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org"]

[version]
main = "0.46.4-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"packages/p/pixman/pixman-0.46.4-1-x86_64.pkg.tar.zst" = "e87e665d25a2230a178d8490202e1d677fde5908f68ebedf7d987308fc26fcb6"
