installationWarnings = ["Bento's podman package does not work and there is no binary for podman in bin because podman has no option to load default configuration files (https://docs.podman.io/en/stable/markdown/podman.1.html#configuration-files) from a directory other then `/usr/share/containers` while still allowing the user to override some of the configuration files with files in `$HOME/.config/containers`. Apparently config parsing will be consolidated in podman 6, so hopefully this option can be added then."]
homepage = "https://podman.io/"
urlInMirror = "podman-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org/packages/p/podman"]

[version]
main = "5.6.1-1"

[architectureNames]
amd64 = "x86_64"

[directSharedLibraryDependencies]
"usr/bin/podman" = [
    "libsubid.so.5",
    "libgpgme.so.45",
    "libseccomp.so.2",
    "libgcc_s.so.1",
    "libc.so.6",
]

[checksums]
"podman-5.5.2-1-x86_64.pkg.tar.zst" = "04b6fe029d0893223241b052e018ae295cd85ccd0b68c6f72628c74905bc09aa"
"podman-5.6.0-1-x86_64.pkg.tar.zst" = "2d70195dc71ef2610031c3b8d290eab88525b1427cbe3c891cd76d32f9e9c4f1"
"podman-5.6.1-1-x86_64.pkg.tar.zst" = "d86ca66d50749b72430bf3d226dc45ca92c814a315a9b06e9763349d2d7f5859"
