homepage = "https://podman.io/"
urlInMirror = "packages/p/podman/podman-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org"]

[version]
main = "5.6.0-1"

[architectureNames]
amd64 = "x86_64"

[directlyDependentSharedLibraries]
"usr/bin/podman" = [
    "libsubid.so.5",
    "libgpgme.so.45",
    "libseccomp.so.2",
    "libgcc_s.so.1",
    "libc.so.6",
]

[checksums]
"packages/p/podman/podman-5.5.2-1-x86_64.pkg.tar.zst" = "04b6fe029d0893223241b052e018ae295cd85ccd0b68c6f72628c74905bc09aa"
"packages/p/podman/podman-5.6.0-1-x86_64.pkg.tar.zst" = "2d70195dc71ef2610031c3b8d290eab88525b1427cbe3c891cd76d32f9e9c4f1"
