knownIssues = [
    "The `librt.so.1`, `libdl.so.1`, `libpthread.so.1`, and `libtinfo.so.6` shared library dependencies are not specified because they have not been packaged in bento, roc seems to work either without them or by using the system packages, and roc is being rewritten in zig (https://github.com/roc-lang/roc/tree/main/src), so the shared library dependencies will probably change soon anyways"
]
homepage = "https://www.roc-lang.org/"
description = "A fast, friendly, functional language."
rootPath = "roc_nightly-linux_${architecture}-${version.other}-${version.commit_hash}"
licenses = ["UPL-1.0"]
mirrors = ["https://github.com/roc-lang/roc/releases/download/"]
urlInMirror = "${version.main}/roc-linux_${architecture}-${version.main}.tar.gz"
compression = ".tar.gz"

[version]
main = "alpha4-rolling"
other = "2025-09-09"
commit_hash = "d73ea109"

[architectureNames]
amd64 = "x86_64"

[directSharedLibraryDependencies]
"roc" = [
    "libm.so.6",
    "libz.so.1",
    "libzstd.so.1",
    "libstdc++.so.6",
    "libgcc_s.so.1",
    "libc.so.6",
    "ld-linux-x86-64.so.2",
]

[checksums]
"alpha4-rolling/roc-linux_x86_64-alpha4-rolling.tar.gz" = "96e8be05e6f7176433ada74532ff36a62b8dc44c5247a82cdf919f2dadc5178b"
