homepage = "https://github.com/shadow-maint/shadow"
urlInMirror = "shadow-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org/packages/s/shadow"]

[version]
main = "4.18.0-1"

[architectureNames]
amd64 = "x86_64"

[directSharedLibraryDependencies]
"usr/bin/getsubids" = ["libsubid.so.5"]

[checksums]
"shadow-4.18.0-1-x86_64.pkg.tar.zst" = "4aaee1e60d263afa755504bc35a28c785a54cdb0f9c0fa33b559642f7a2f49b4"
