homepage = "https://github.com/simdjson/simdjson"
description = "A C++ library to see how fast we can parse JSON with complete validation."
licenses = ["Apache-2.0"]
urlInMirror = "simdjson-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org/packages/s/simdjson"]

[version]
main = "1:4.0.7-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"simdjson-1:3.13.0-1-x86_64.pkg.tar.zst" = "1dbfffaa176ed7ca5b5feed9e31918ea7d5c82e0a4b28c24a6a82f09d54e523f"
"simdjson-1:4.0.7-1-x86_64.pkg.tar.zst" = "93e1a6f9d321d7d2a3087e1da48e564773df45b43fc755f86c0e57ab0bd52aa8"
