homepage = "https://www.sqlite.org/"
url = "https://archive.archlinux.org/packages/s/sqlite/sqlite-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"

[version]
main = "3.50.4-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"https://archive.archlinux.org/packages/s/sqlite/sqlite-3.50.3-1-x86_64.pkg.tar.zst" = "d17eead32978952ff6f62b96873697028fa5e49230516467ad52c82bba547265"
"https://archive.archlinux.org/packages/s/sqlite/sqlite-3.50.4-1-x86_64.pkg.tar.zst" = "59b2cb2835eadeb11bf40a5f13ee1bc400d97311de7512dda9d056c8a3c4f10e"
