homepage = "https://www.github.com/systemd/systemd"
url = "https://archive.archlinux.org/packages/s/systemd-libs/systemd-libs-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "257.7-2"
architectureNames.amd64 = "x86_64"
