homepage = "https://tinysparql.org/"
url = "https://archive.archlinux.org/packages/t/tinysparql/tinysparql-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "3.9.2-2"
architectureNames.amd64 = "x86_64"
