homepage = "https://typst.app/"
description = "Limitless power to write, create, and automate anything that you can fit on a page."
rootPath = "typst-${architecture}-unknown-linux-musl"
licenses = ["Apache-2.0"]
mirrors = ["https://github.com/typst/typst/releases/download"]
urlInMirror = "v${version.main}/typst-${architecture}-unknown-linux-musl.tar.xz"
compression = ".tar.xz"

[version]
main = "0.13.1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"v0.13.1/typst-x86_64-unknown-linux-musl.tar.xz" = "7d214bfeffc2e585dc422d1a09d2b144969421281e8c7f5d784b65fc69b5673f"
