homepage = "https://github.com/neovim/unibilium"
urlInMirror = "unibilium-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org/packages/u/unibilium"]

[version]
main = "2.1.2-1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"unibilium-2.1.2-1-x86_64.pkg.tar.zst" = "4aff3d15c068582898236e442b1c018683af194afaea1e13da697f5fd5c479de"
