homepage = "https://www.vulkan.org/"
url = "https://archive.archlinux.org/packages/v/vulkan-icd-loader/vulkan-icd-loader-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "1.4.321.0-1"
architectureNames.amd64 = "x86_64"
