homepage = "https://github.com/bugaevc/wl-clipboard"
url = "https://archive.archlinux.org/packages/w/wl-clipboard/wl-clipboard-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "1:2.2.1-3"
architectureNames.amd64 = "x86_64"

[directlyDependentSharedLibraries]
"usr/bin/wl-copy" = ["libwayland-client.so.0", "libc.so.6"]
"usr/bin/wl-paste" = ["libwayland-client.so.0", "libc.so.6"]
