homepage = "https://github.com/atx/wtype"
description = "xdotool type for wayland"
licenses = ["MIT"]
urlInMirror = "wtype-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
mirrors = ["https://archive.archlinux.org/packages/w/wtype"]

[version]
main = "0.4-2"

[architectureNames]
amd64 = "x86_64"

[checksums]
"wtype-0.4-2-x86_64.pkg.tar.zst" = "36ce49003b9e741b85463574d3ab35316bd27d0ef950db0e1f8540d75d68409d"

[directSharedLibraryDependencies]
"usr/bin/wtype" = [
    "libwayland-client.so.0",
    "libxkbcommon.so.0",
    "libc.so.6",
]
