homepage = "https://tukaani.org/xz/"
url = "https://archive.archlinux.org/packages/x/xz/xz-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "5.8.1-1"
architectureNames.amd64 = "x86_64"
