homepage = "https://zen-browser.app/"
description = "Welcome to a calmer internet"
licenses = ["Mozilla Public License Version 2.0"]
url = "https://github.com/zen-browser/desktop/releases/download/${version.main}/zen-${architecture}.AppImage"
compression = "none"
filesToMakeExecutable = ["."]
version.main = "1.15.1b"
architectureNames.amd64 = "x86_64"

[checksums]
"https://github.com/zen-browser/desktop/releases/download/1.14.11b/zen-x86_64.AppImage" = "301a0825fe1d80624ef4d31910b0f49264319f513581f02de134daa440107d7d"
"https://github.com/zen-browser/desktop/releases/download/1.15.1b/zen-x86_64.AppImage" = "fcc7883e3d5b637928911919e108f9f17131299e6989cd23f0fb4793aeaf71fc"
