homepage = "https://ziglang.org/"
urlInMirror = "zig-${architecture}-linux-${version.main}.tar.xz"
rootPath = "zig-${architecture}-linux-${version.main}"
compression = ".tar.xz"
filesToMakeExecutable = ["zig"]
mirrors = [
    "https://pkg.machengine.org/zig",
    "https://zigmirror.hryx.net/zig",
    "https://zig.linus.dev/zig",
    "https://zig.squirl.dev",
    "https://zig.mirror.mschae23.de/zig",
    "https://zigmirror.meox.dev",
]

[version]
main = "0.15.1"

[architectureNames]
amd64 = "x86_64"

[checksums]
"zig-x86_64-linux-0.14.1.tar.xz" = "24aeeec8af16c381934a6cd7d95c807a8cb2cf7df9fa40d359aa884195c4716c"
"zig-x86_64-linux-0.15.1.tar.xz" = "c61c5da6edeea14ca51ecd5e4520c6f4189ef5250383db33d01848293bfafe05"
