homepage = "https://ziglang.org/"
url = "https://ziglang.org/download/${version.main}/zig-${architecture}-linux-${version.main}.tar.xz"
rootPath = "zig-${architecture}-linux-${version.main}"
compression = ".tar.xz"
filesToMakeExecutable = ["zig"]
version.main = "0.14.1"
architectureNames.amd64 = "x86_64"

[checksums]
"https://ziglang.org/download/0.14.1/zig-x86_64-linux-0.14.1.tar.xz" = "24aeeec8af16c381934a6cd7d95c807a8cb2cf7df9fa40d359aa884195c4716c"
