homepage = "https://facebook.github.io/zstd/"
url = "https://archive.archlinux.org/packages/z/zstd/zstd-${version.main}-${architecture}.pkg.tar.zst"
compression = ".tar.zst"
version.main = "1.5.7-2"
architectureNames.amd64 = "x86_64"
